name 'picnic-basket'
maintainer 'Chef Software, Inc'
maintainer_email 'mattstratton@chef.io'
license 'apache2'
description 'Installs/Configures picnic-basket'
long_description 'Installs/Configures picnic-basket'
version '0.1.0'
depends 'vagrant', '~> 0.2.2'
depends 'chocolatey', '~> 0.4.0'
# depends 'virtualbox'
depends 'git', '~> 4.0.2'
